baseURL: "https://ebintomy.github.io/"  # Your GitHub Pages URL
languageCode: "en-us"
title: "Ebin Tomy"

# Enable raw HTML
markup:
  goldmark:
    renderer:
      unsafe: true

# Basic parameters
params:
  description: "Personal website of Ebin Tomy"

# Create default archetypes
taxonomies:
  category: categories
  tag: tags

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON